[package]
name = "maidsafe_dns"
version = "0.0.1"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/maidsafe_dns/latest"
repository = "https://github.com/maidsafe/maidsafe_dns"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"
